"""Add post table

Revision ID: 5eb91e1a79ca
Revises: 
Create Date: 2026-06-16 10:22:52.694018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5eb91e1a79ca'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'post', ['id'])
    op.create_unique_constraint(None, 'rate_limits', ['id'])
    op.create_unique_constraint(None, 'tiers', ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'tiers', type_='unique')
    op.drop_constraint(None, 'rate_limits', type_='unique')
    op.drop_constraint(None, 'post', type_='unique')
    # ### end Alembic commands ###
